INSERT INTO `bamazon`.`products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Harry Potter and the Cursed Child', 'Books', '17.98', '20');
INSERT INTO `bamazon`.`products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Fantastic Beasts and Where to Find Them', 'Books', '14.99', '20');
INSERT INTO `bamazon`.`products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Star Trek Beyond', 'Movies', '19.96', '20');
INSERT INTO `bamazon`.`products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Finding Dory', 'Movies', '19.98', '20');
INSERT INTO `bamazon`.`products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Perplexus', 'Toys & Games', '16.99', '20');
INSERT INTO `bamazon`.`products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Harry Potter Wand', 'Toys & Games', '29.95', '20');
INSERT INTO `bamazon`.`products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('ALPS Mountaineering Meramac 2-person Tent', 'Sports & Outdoors', '74.59', '20');
INSERT INTO `bamazon`.`products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Osprey Stratos 36 Backpack', 'Sports & Outdoors', '111.96', '20');
INSERT INTO `bamazon`.`products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Pokemon Sun - Nintendo 3DS', 'Video Games', '39.99', '20');
INSERT INTO `bamazon`.`products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Pokemon Moon - Nintendo 3DS', 'Video Games', '39.99', '20');